In [35]:
import pandas as pd
from datetime import datetime as dt

In [46]:
wmt_csv = "wmt_csv.csv"
amz_csv = "amzn_csv.csv"
cos_csv = "cost_csv.csv"
tgt_csv = "tgt_csv.csv"
wmt_df = pd.read_csv(wmt_csv)
amz_df = pd.read_csv(amz_csv)
cos_df = pd.read_csv(cos_csv)
tgt_df = pd.read_csv(tgt_csv)

,Date,Revenue USD Mil,Gross Margin %,Operating Income USD Mil,Operating Margin %,Net Income USD Mil,Earnings Per Share USD,Dividends USD,Payout Ratio % *,Shares Mil,Book Value Per Share * USD,Operating Cash Flow USD Mil,Cap Spending USD Mil,Free Cash Flow USD Mil,Free Cash Flow Per Share * USD,Working Capital USD Mil
0,2011-01,67390,30.9,5252,7.8,2920,4.00,0.84,21.0,729,22.00,5271,-2129,3142,4.31,7143
1,2012-01,69865,30.9,5322,7.6,2929,4.28,1.10,25.7,683,23.64,5434,-4368,1066,1.56,2162
2,2013-01,73301,30.4,5210,7.1,2999,4.52,1.32,28.0,663,25.13,5325,-3277,2048,4.27,2357
3,2014-01,72596,29.5,3838,5.3,1971,3.07,1.58,40.6,641,25.56,6520,-3453,3067,4.57,-1204
4,2015-01,72618,29.4,4535,6.2,-1636,-2.58,1.90,76.0,640,25.57,4439,-1786,2653,2.56,2351
5,2016-01,73785,29.5,4910,6.7,3363,5.31,2.16,47.0,632,22.01,5844,-1438,4406,7.18,1508
6,2017-01,69495,29.7,4969,7.2,2737,4.69,2.32,42.1,583,19.90,5436,-1547,3889,5.70,-718
7,2018-01,71879,28.9,4312,6.0,2934,5.29,2.44,50.9,550,20.49,6923,-2533,4390,8.35,-637
8,2019-01,75356,29.3,4110,5.5,2937,5.51,2.52,41.7,533,21.23,5973,-3516,2457,5.00,-2495
9,2020-01,78112,29.8,4658,6.0,3281,6.36,2.60,41.4,516,22.78,7117,-3027,4090,6.67,-1585

In [47]:
wmt_df = wmt_df.dropna(axis=1, how='any')
amz_df = amz_df.dropna(axis=1, how='any')
cos_df = cos_df.dropna(axis=1, how='any')
tgt_df = wmt_df.dropna(axis=1, how='any')

In [48]:
wmt_df['Date'] = pd.to_datetime(wmt_df['Date'],format='%Y-%m').dt.strftime('%Y')
amz_df['Date'] = pd.to_datetime(amz_df['Date'],format='%Y-%m').dt.strftime('%Y')
tgt_df['Date'] = pd.to_datetime(tgt_df['Date'],format='%Y-%m').dt.strftime('%Y')
cos_df['Date'] = pd.to_datetime(cos_df['Date'],format='%Y-%m').dt.strftime('%Y')

In [50]:
tgt_df

,Date,Revenue USD Mil,Gross Margin %,Operating Income USD Mil,Operating Margin %,Net Income USD Mil,Earnings Per Share USD,Dividends USD,Shares Mil,Operating Cash Flow USD Mil,Cap Spending USD Mil,Free Cash Flow USD Mil,Working Capital USD Mil
0,2010,408214,25.4,23950,5.9,14335,3.71,1.09,3877,26249,-12184,14065,-7230
1,2011,421849,25.3,25542,6.1,16389,4.47,1.21,3670,23643,-12699,10944,-6591
2,2012,446950,25.0,26558,5.9,15699,4.52,1.46,3474,24255,-13510,10745,-7325
3,2013,469162,24.9,27801,5.9,16999,5.02,1.59,3389,25591,-12898,12693,-11878
4,2014,476294,24.8,26872,5.6,16022,4.88,1.88,3283,23257,-13115,10142,-8160
5,2015,485651,24.8,27147,5.6,16363,5.05,1.92,3243,28564,-12174,16390,-1994
6,2016,482130,25.1,24105,5.0,14694,4.57,1.96,3217,27389,-11477,15912,-4380
7,2017,485873,25.6,22764,4.7,13643,4.38,2.00,3112,31530,-10619,20911,-9239
8,2018,500343,25.4,20437,4.1,9862,3.28,2.04,3010,28337,-10051,18286,-18857
9,2019,514405,25.1,21957,4.3,6670,2.26,2.08,2945,27753,-10344,17409,-15580